### ISSUE TITLE
Profile admin performance impact of plugin

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#1036]
We've had several reports that the plugin is materially impacting the performance of wp-admin, across all screens.

See here: https://wordpress.org/support/topic/admin-area-running-slow?replies=3#post-8154791

Let's profile what's going on and do as much as we can to remove any performance impact.

**Comment by pdewouters** [comment]
For me all admin pages load quite fast, except the BUWP admin page which can take around 5 seconds. I noticed `get_site_size()` gets called a bunch of times and each time makes a DB request. If I comment it out, it loads 3 seconds faster.
there's still something else slowing it down though, it seems.

**Comment by accaldwell** [comment]
A bit more info from two sites that experienced this problem (I am one of the people who reported in the forum):

Wordpress: 4.4.2
PHP: 5.6.18
MySQL (MariaDB): 5.5.5
Linux: 4.4.2 on CentOS Linux 64-bit release 7.0.1406

Symptoms were extremely long load times (over a minute in my estimation) on any wp-admin/ page (not exclusive to BackUpWordPress pages), complaints about database timeouts despite the database being fine (phpmyadmin worked fine, a support ticket to the host did not indicate anyone else was having database issues, and my issues went away on my sites when disabling this plugin).

Running on shared hosting, so I can't get any lower level details for you, hope this helps.

**Comment by katmoody** [comment]
Not positive but wondering if something like this could also be part of the same issue: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/4402445036

In this ticket, his site goes down because of 'too many processes' and CPU usage even though it was working previously. We have had problems with his host in the past but I've seen this issue a couple times - would it be better to have a new ticket for this or attribute it to this issue? Or is there a way to confirm it is, in fact, related to hosting limitations only?

**Comment by joshuafredrickson** [comment]
I've noticed this on my development server (shared hosting) across several sites. Activating BUWP 3.5 slows every WP-Admin page to a 3-minute load time, not just the BUWP pages.

The server isn't experiencing any CPU usage issues and BUWP worked great in versions prior to 3.5. All sites are running WP 4.4.2, PHP 5.5.31.

Running P3 Profiler shows what happens when BUWP is activated:

![buwp slow admin](https://cloud.githubusercontent.com/assets/3533660/14092932/ce8f304e-f50f-11e5-9157-8e39f94562c1.JPG)

Thankfully, the live sites I administer have the same configuration and work just fine. Otherwise, I'd be stuck downgrading all of them.

Shouldn't be too hard to track down since it's occurring on every WP-Admin page... ?

**Comment by pdewouters** [comment]
I think we can avoid calling https://github.com/humanmade/backupwordpress/blob/master/functions/core.php#L298 on every admin page load, if we set a flag to keep track of whether the default schedules have been set up and bail before instantiating the Schedule class.
Every call to `refresh_schedules()` causes a DB query, which could be slower on some servers.
`$schedules = $wpdb->get_col( "SELECT option_name from $wpdb->options WHERE option_name LIKE 'hmbkp\_schedule\_%'" );`

**Comment by willmot** [comment]
I find it hard to imagine that the DB query is adding 3 minutes to every page load so my spidey sense is that there has to be something else going on here, although I don't know what :8ball:.

You're right though, we should avoid calling `refresh_schedules` as much as we can, we should also refactor it away from `$wpdb` as we're losing out on object cache by doing so.

**Comment by joshuafredrickson** [comment]
Sorry I don't have more to offer at this point... I haven't had a enough spare time to dig in. 

However, I would agree that it doesn't seem like a DB issue. Here's a comparison from P3 before and after BUWP's been activated:

![buwp-p3](https://cloud.githubusercontent.com/assets/3533660/14110950/54c58bf8-f58e-11e5-891e-633ec612fa82.png)

Not much difference between any of the numbers with the exception of PHP ticks, which isn't all that helpful.

I should also note that it's not just WP-Admin page loads that are slow. Calls to `load-scripts.php`, `load-styles.php` and `admin-ajax.php` all take just as long. Perhaps the page takes 30 seconds to load, but then we're waiting an additional 30 seconds for each of those assets to load as well.

Currently, I'm only experiencing this issue on my shared dev server, which has a larger than average number of files on it. Is there possibly a filescan that's causing things to slow on sites with large amounts of files? I/O doesn't reflect in CPU or memory usage. Just a guess at this point.

**Comment by pdewouters** [comment]
Yes, it might be the directory scanner that is causing this.

**Comment by katmoody** [comment]
Can we compare the plugins installed on these sites? I wonder if we might be seeing the effect of multiple scans going at the same time? I've noticed with WordFence and Sucuri plugins, the scanning is usually set to continuous. By itself, it's fine, but in addition to further scanning, it bogs down the site admin in my testing. I'm not testing as deeply as you guys, but just wonder if it is something to consider?

**Comment by katmoody** [comment]
In responding to a ticket in Intercom, this person is having to deactivate BWP because of the effect to the running of his admin :( 

The initial information seems to be similar: it worked fine prior to 3.5, the admin is slowing in loading by minutes, sometimes, deactivating the plugin reverses all effects.

**Comment by accaldwell** [comment]
A brief test with BWP 3.6 shows the issue appears to be resolved for me. I only tested for a few minutes though, because I have since moved to another backup solution.

**Comment by hlorenz** [comment]
I upgraded yesterday from something <3.5 to 3.6 and it killed my admin panel. Had to deactivate the plugin..

**Comment by cnc137** [comment]
I ran into the same thing on a client's WordPress test website. All the pages under the WordPress Dashboard run extremely slow and take a very long time to load, if they load at all, when BackupWordPress is activated. If I deactivate the BackupWordPress plugin everything goes back to normal and loads quickly again.

The site is running the following:

- WordPress 4.5.2 
- BackupWordPress 3.6.1 - Activated
- Members 1.1.1 - Activated
- Akismet 3.1.10 - Deactivated

No other plugins are installed at the moment. I tried repairing and optimizing the database in phpMyAdmin, since that has helped a few of my WordPress sites in the past when they were running slow, but that didn't resolve the problem.

Let me know if there is any other information I can provide to help resolve this problem.

**Comment by katmoody** [comment]
Hey there @cnc137 - offhand have you tried to enable any kind of debugging methods? Or perhaps the Query Monitor plugin? Having a chance to see what processes are running which are slowing down the admin would be very helpful. I have logs from a test site, but I'm not sure whether the limits imposed on some hosts might be exasperating the situation or not? 

I'm sure the developers will have more input. Thanks so much for your help is figuring this one out.

**Comment by wwwolf3** [comment]
Same problem as others with admin interface slowing to a crawl when plugin enabled, on two different sites (on same server). Environment:
Apache + PHP 5.6
WordPress 4.5.2
BackupWordPress 3.6.1 - Activated
I tried disabling other plugins (incl WordFence) - no change until disabled BWP.
I've enabled error logging, and it throws the following error (exactly) whenever I try to navigate to any page in the back end (tho obv I've substituted [user] for the account in the path!):

[14-May-2016 16:24:16 UTC] PHP Notice:  Undefined offset: 0 in /home/[user]/public_html/wp/wp-content/plugins/backupwordpress/vendor/symfony/process/Pipes/AbstractPipes.php on line 142

Hope that's helpful. Meantime, have had to disable BWP on both sites. Thanks.

**Comment by leanda** [comment]
I'm having the same issue, dashboard is pretty unusable with a combination of BackupWordPress and Wordfence installed. If I disable one or the other it speeds up again.

WordPress 4.5.2
BackupWordPress 3.6.1
Wordfence Security 6.1.8

Please let me know if I can provide any further information.

**Comment by willmot** [comment]
@dashaluna let's tackle this one together next week

**Comment by leanda** [comment]
Any news?

**Comment by willmot** [comment]
I put some time into trying to reproduce this and have been unable too. I tried:

- Locally
- On GoDaddy Managed WordPress Hosting
- On Pantheon
- On WP Engine

On all three I couldn't reproduce the issue, even with other plugins like WordFence active.

Would someone here who's running into the issue be able to grant me temporary access to their site so I can see the issue in action and debug. Ideally, I'd get an administrator-level user account as well as FTP / SFTP access. If you're up for that then please get in touch directly at tom@hmn.md.

**Comment by Aetles** [comment]
Not sure if it is related to the other reports, but on a multisite with 200+ sites I ran into the issue of BUWP calling `SHOW TABLE STATUS` on every admin page (or at least, all the pages I was looking at) and that added around 10-14 seconds to the load time (to a total of 15-17 seconds, disabling BUWP got it down to 2-3 seconds).

**Comment by willmot** [comment]
Thanks for reporting @Aetles, I've added some based transient caching around that so at lest we're not calling on all page loads.

Could you try https://github.com/humanmade/backupwordpress/pull/1077 and see if it helps.

**Comment by willmot** [comment]
Ok I think I may have cracked this, I'd love it if one or more of the folks on this thread could test out https://github.com/humanmade/backupwordpress/pull/1077

**Comment by Aetles** [comment]
I applied the changes in #1077 and yes, it seems to work! Load went from 12 to 2 seconds on the admin page I was testing.

**Comment by willmot** [comment]
Thanks for the feedback @Aetles 👍

**Comment by leanda** [comment]
Brilliant! I've just tested this and it works a treat.

**Comment by willmot** [comment]
Fantastic, thanks @leanda!

I'm going to close this issue as resolved and we'll merge and release #1077. Thanks everyone!
