### ISSUE TITLE
Incorrect File Sizes Recorded under Exclusions

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1058]
Pretty sure this might be universal - have seen on every site I've looked at running BWP. 

When you go under exclusions, the files sizes are listed incorrectly. So if all the files together are 600 MB, and the uploads folder is actually 300 MB in size, it just shows 300 B in size. 

![tools php 1](https://cloud.githubusercontent.com/assets/5481211/14501030/76fe1ef2-0172-11e6-81cc-20b6bf20891e.jpg)

**Comment by dashaluna** [comment]
@willmot @pdewouters I wanted to double check, that we should display the excluded files/folders in the `Your site` table? If so, then there is a bit of bug with size display for folders. Screenshot below. Shat should it be? Just the full size of the folder (i.e. 13MB) rather than `%s of %s` pattern?

<img width="1236" alt="screen shot 2016-06-06 at 15 07 18" src="https://cloud.githubusercontent.com/assets/2185972/15824815/eb340362-2bf8-11e6-89ff-c9613c2dc048.png">

**Comment by willmot** [comment]
Ah good catch, if the whole folder is excluded then it should probably say `0 of 13 MB` included?

**Comment by dashaluna** [comment]
Opened WP ticket. https://core.trac.wordpress.org/ticket/37037 If I figure out how to submit the solution, I'll do that :) Will look into that.

**Comment by dashaluna** [comment]
@willmot isn't that gonna be a bit confusing? We're displaying a list of excluded files/folders under `Currently Excluded`. I'd expect them NOT to show in the `Your Site` list anymore? Also, the column name is `Included Size`. If it's gonna be `0 of 13 MB` for excluded folders. Then for excluded files it should be really `0`?

![manage backups wordpress org wordpress](https://cloud.githubusercontent.com/assets/2185972/15825999/bd099f42-2bfd-11e6-82a9-6ce9f4349962.png)

**Comment by willmot** [comment]
Yeah, that is pretty confusing I guess 👍 

Any ideas how we could do it better?

**Comment by dashaluna** [comment]
@willmot I feel this should be a separate ticket - we need more discussion on this and I don't want to block this bug fix. I'll open a new issue.

**Comment by willmot** [comment]
@dashaluna great thanks!
