### ISSUE TITLE
Fatal error "Function name must be a string"

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1134]
Had a potential Fatal Error come up in the WordPress forum: https://wordpress.org/support/topic/fatal-error-lost-control-of-site-during-install/#post-8380968

> During an install of BackUpWordpress I got:
> 
> Fatal error: Function name must be a string in /home/ssald9753/public_html/bng/wp-content/plugins/backupwordpress/vendor/symfony/process/Process.php on line 1364
> 
> I then got this error from all backend WordPress menu choices and I now get it when I try to login.
> I looked at line 1364:
> $callback($type === self::STDOUT ? self::OUT : self::ERR, $data);
> but not seeing what code needed to be changed experimented with changing the file name. I then got a similar error from the calling php file.
> 
> Not sure of WP version as I cant see the back anymore. Site is still running up front.
> In other words I’ve lost my site.

**Comment by willmot** [comment]
I looked into this as did @shadyvb and we were unable to either reproduce or figure out a code path that would lead to this happening.

We're also on a legacy symfony branch (2.8.x) as 3.x is PHP 5.5 only. It could be that this is a bug in symfony that has since been fixed.

@katmoody could you keep posting here each time this comes up in support so we can get a sense as to how prevalent it is. So far I've only seen it raised twice.

**Comment by katmoody** [comment]
Since this hasn't come up again I am closing this as an infrequent issue for now.
