### ISSUE TITLE
Probably incorrect value from new Site_Size()

### ISSUE THREAD

**Issue by rrikesh** [humanmade/backupwordpress#1148]
I'm getting the warning

> Your server only has 16 GB of disk space left which probably isn't enough to complete a backup. Try deleting some existing backups or other files to free up space.

I earlier had a warning about 2 GB left and I deleted all backups from the backup folder.  Now, I have 16GB of free space as mentioned in the warning above. It matches the result I get by doing the `df -h` command.

The command `du -hs /website/path/here/` says that the site is 1.5GB.

However, if I print the size of `$backup_size` variable in the `disk_low_space()` function, I get 20 GB (It's defined as twice of the site size).

I ran this code just before the `return` in `disk_low_space()`:

>   var_dump( array( size_format($backup_size) , size_format($disk_space) ) );

Results:

>  array(2) { [0]=> string(5) "20 GB" [1]=> string(5) "16 GB" } 

Any idea what causes the discrepancy in the Site_Size() value?

Thanks

**Comment by katmoody** [comment]
Hey there @rrikesh - thank you for the detailed information on this one. The developers have been working on this one for a while and though I'm not positive what they determined the discrepancy was caused by, they do have a beta that addresses this issue if you'd like to try it out for us. 

Here's a link to the beta if you'd like to give it a check. Let us know how it works for you, if you would? And if it addresses everything you've identified above - we think it will! 

https://github.com/humanmade/backupwordpress/files/617058/BackUpWordPress-3.6.3-beta.zip

**Comment by rrikesh** [comment]
Worked perfectly 👌🏻

Thank you!
