### ISSUE TITLE
Use Grunt

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#444]
The benefit of using Grunt in the plugin:
- automatic CSS minification
- automatic JS minification
- automatic internationalization ( https://npmjs.org/package/grunt-wp-i18n )
- Coding standards checking ( also checks escaping )

Negative:
- could higher the barrier of entry for potential contributors? We don't have many as it is though, so not really an issue

**Comment by palepurple** [comment]
I tried to patch & test your plugin but couldn't get grunt installed and setup. 

The backupwordpress-dev url above doesn't work.

When I try to use grunt, I get a cryptic error which seems to imply 'files' isn't defined -

<pre>
Running "newer:concat:css" (newer) task
Warning: Cannot read property 'files' of undefined Use --force to continue.
Aborted due to warnings.
</pre>

npm v2.11.3
grunt 0.4.5

In the end, I just downloaded the latest .zip, unzipped, edited, re-zipped, tested. 

I'm probably doing something stupid with npm/grunt which I have no experience with, but it's definitely a barrier to contributing!

**Comment by pdewouters** [comment]
@palepurple we only really use the Grunt tasks for automating release stuff so you don't really need the Grunt setup to be able to contribute.
I'll look into this error though

**Comment by palepurple** [comment]
Hello again - I felt I needed to make a .zip so I could upload my modified variant of the plugin to a wordpress instance and test it. 

Could you provide/include instructions for building a upload-able .zip then?

**Comment by pdewouters** [comment]
Hello

So you can run grunt build:copy and that will create a /build/ subdirectory
that you can then cut/paste somewhere else and zip it up

**Comment by palepurple** [comment]
"Warning: Task 'build:copy' not found. Use --force to continue". 
No doubt I have the wrong grunt version or something.

I ended up downloading a released .zip, and replacing one file in it, in order to test....
Hopefully the pull request is of use.....
Thanks.

**Comment by pdewouters** [comment]
my bad, it's `grunt copy:build` :sweat:

**Comment by palepurple** [comment]
Ah hah! That does something. Thank you!
