### ISSUE TITLE
Use wp_filesystem to fix perms on backups dir

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#55]
That way we can get rid of warning messages.

**Comment by pdewouters** [comment]
Yes, we should use WP_Filesystem to write any files to the local filesystem

**Comment by willmot** [comment]
> Yes, we should use WP_Filesystem to write any files to the local filesystem

100%, except in the case where are writing files on a cron (as we do with backups), in those cases it's not possible for people to enter their username and password if they need to enter their FTP details.

**Comment by pdewouters** [comment]
Would fix this error too because we won't need to run this check

`WordPress 4.2 - backupwordpress Versión 3.2.4. Error: {"php":{"d48b02d27a9fb68b7aa4cd1f88ec329a":"shell_exec(): Unable to execute 'whoami', \/hsphere\/local\/home2\/aarte103\/elsolnews.com\/wp-content\/plugins\/backupwordpress\/functions\/interface.php, 114"}}`

Although we still need to use `shell_exec` in some places so might be worth determining the path to the php executable?

**Comment by willmot** [comment]
That's not an error related to the `php` executable, that just indicating that this is a PHP error message. The error is that the `whoami` executable couldn't be executed. You're right though that we could remove all this if we switch to using `WP_Filesystem`

**Comment by pdewouters** [comment]
@willmot I say that because I found a similar issue on stack overflow: https://github.com/humanmade/backupwordpress/issues/808

**Comment by willmot** [comment]
Fixed by https://github.com/humanmade/backupwordpress/pull/833
