### ISSUE TITLE
Test whether --single-transaction is available before trying to use it

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#708]
_From @pdewouters on August 30, 2013 11:15_

````
mysqldump: unrecognized option --single-transaction
````
mysqldump Ver 8.22 Distrib 3.23.52, for suse-linux (i686)`

I had a couple of questions about this single transaction business. Any idea if it's something we can fix?

http://wordpress.org/support/topic/plugin-backupwordpress-backup-fails-with-mysqldump-unrecognized-option?replies=3#post-4587313

_Copied from original issue: humanmade/hm-backup#40_

**Comment by willmot** [comment]
_From @joehoyle on September 5, 2013 15:37_

So this should be pushing an error to `$stderr` here: https://github.com/humanmade/hm-backup/blob/master/hm-backup.php#L693 which in turn should mean the mysqldump fallback method is used. So something in that process is wrong - I imagine something funky is happening there. I would try changing the `mysqldump` single transaction args to something like `foobar` which would essentially trigger the same error for you locally so you can test what happens if you pass `mysqldump` an invalid arg.

**Comment by willmot** [comment]
We could also do with checking whether `--single-transaction` is usable before passing it as an arg.

**Comment by willmot** [comment]
> So this should be pushing an error to $stderr here: https://github.com/humanmade/hm-backup/blob/master/hm-backup.php#L693 which in turn should mean the mysqldump fallback method is used.

The fallback method will be being used, it's just that currently we still report that error to the user (which we should stop doing https://github.com/humanmade/backupwordpress/issues/429).

**Comment by willmot** [comment]
This can safely be ignored as we'll simply fallback to imysqldump.

**Comment by pojda** [comment]
Sorry to bring back such an old thread, but the proposed solution here (imysqldump) by @willmot  isn't working. This is what I get when I try to backup my DB:

`Mysqldump: mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 1044: Access denied for user 'XXX'@'localhost' to database 'XXX' when using LOCK TABLES
IMysqldump: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'XXX'@'localhost' to database 'XXX'`

It looks like both ways try to lock tables and fail for the same reason (hint: code 1044). When I dump these myself on CLI I have to force --single-transaction otherwise it doesn't work.

Can you please take a look at this once more?

**Comment by katmoody** [comment]
Hey there @pojda - from what I know on this one, that error means that the `LOCK TABLES` privilege isn't enabled for the user. Once those privileges are fully enabled this error is resolved. Can you check that on your end for me? Thanks!
