### ISSUE TITLE
"PHP is running on Safe Mode"

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#725]
So had 1 or two reports of PHP running in Safe Mode when it is not. 

I read something about safe mode being depreciated?

**Comment by willmot** [comment]
Yeah I keep seeing this also, strange. our `safe_mode` detection code is pretty simply (basically just `ini_get( 'safe_mode' ) == 'yes'`) and I've never yet had a case that didn't end up just being user / host error (IE the host says they are not on safe mode but when you send them proof that `ini_get( 'safe_mode' )` returns `Yes` they then say "oh yeah, turns out it was on".

It was deprecated in 5.3 and removed completely in 5.4. Calling `ini_get( 'safe_mode' )` on my local PHP 5.5 install returns `false`.

**Comment by pdewouters** [comment]
We're checking for `if ( $safe_mode && strtolower( $safe_mode ) != 'off' )` 
Maybe there are multiple valid values? e.g. off / false / 0 - then we could check with a whitelist

**Comment by willmot** [comment]
Closing this out, we haven't seen the issue for a while and Safe Mode is going away anyway having been deprecated in PHP 5.3 and completely removed in PHP 5.4
