### ISSUE TITLE
Schedule sentence incomplete

### ISSUE THREAD

**Issue by richardswain** [humanmade/backupwordpress#956]
The schedule sentence is incomplete when there are no services enabled.

![screen shot 2015-12-28 at 16 18 12](https://cloud.githubusercontent.com/assets/888319/12021433/a739c76c-ad7e-11e5-83ce-85b0e678f2de.png)

Maybe
https://github.com/humanmade/backupwordpress/blob/master/admin/schedule-sentence.php#L124

**Comment by willmot** [comment]
@richardswain could you re-test this with https://github.com/humanmade/backupwordpress/releases/tag/3.4-rc1

**Comment by willmot** [comment]
Ran into this locally, the issue is that `$services` can end up containing an array with a single empty value which causes it to pass the check on https://github.com/humanmade/backupwordpress/blob/master/admin/schedule-sentence.php#L130

The empty item is then removed with `array_filter` before the sentence is `echo`'d on https://github.com/humanmade/backupwordpress/blob/master/admin/schedule-sentence.php#L131
